name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: nix build .
  build:
    runs-on: self-hosted
    needs: [check]
    steps:
      - uses: actions/checkout@v4
      - name: Hello World
        run: echo Hello, World!
